### ISSUE TITLE
野火1不支持在线升级吗？

### ISSUE THREAD

**Issue by amwsuhje** [DHDAXCW/DoorNet_Series#5]
![image](https://user-images.githubusercontent.com/55229544/154665252-00c97ad4-0815-4c1a-ba4f-33a6546db80d.png)
提示内存小于2G

**Comment by amwsuhje** [comment]
刷的是[2022.02.05 DoorNet1 formal edition__全插件]ext4格式的固件

**Comment by DHDAXCW** [comment]
小于1g内存不支持升级了，后面我尽量缩小rootfs
