### ISSUE TITLE
 DoorNet1 Plus_全插件请加入应用过滤

### ISSUE THREAD

**Issue by public15** [DHDAXCW/DoorNet_Series#6]
刷全插件版本没有“应用过滤”,能否考虑加上,谢谢
PS:https://www.right.com.cn/forum/thread-8099741-1-1.html 这里的高大全版有应用过滤插件,但是不支持 DoorNet1

**Comment by public15** [comment]
@DHDAXCW 请帮忙处理

**Comment by DHDAXCW** [comment]
ok

**Comment by DHDAXCW** [comment]
https://github.com/DHDAXCW/DoorNet_Series/commit/63b653f2ed54c017c0a79fd3614af575dca77055

**Comment by public15** [comment]
thx,等releases
