### ISSUE TITLE
Doornet1无法开启无线功能

### ISSUE THREAD

**Issue by qinkun1994** [DHDAXCW/DoorNet_Series#8]
### 1、按照如图显示的，保存设置就卡死，重启也无法进入网页配置，必须重新恢复。  
![image](https://user-images.githubusercontent.com/33141476/161285544-4855e014-0d01-44d4-acae-7e799dd95481.png)
 ### 2、 任何保存网卡设置都会一直转圈圈
![image](https://user-images.githubusercontent.com/33141476/161357940-b166f938-c5ea-4f7d-bfd4-261d5e9ce8ee.png)

### 3、点击任何与无线网卡相关的设置，都会导致卡死，共同特征是一个进程CPU占用25%。
9864     1 root     SN   31256   3%   25% /usr/sbin/netdata -nd -c /etc/netdata/netdata.conf
![image](https://user-images.githubusercontent.com/33141476/161285615-fc3997f2-736a-4b28-be1f-0ac8d43634c7.png)

**Comment by qinkun1994** [comment]
我是哪里操作不对吗？  使用的是4月1号 固件，ext4  squashfs都试了一遍。你的这个界面我怎么调不出来？Master模式和工作频率。
![image](https://user-images.githubusercontent.com/33141476/161287384-6eca67d3-982b-4133-85f0-74e91a92f17d.png)

**Comment by qinkun1994** [comment]
`br-lan    Link encap:Ethernet  HWaddr 8E:82:65:61:F3:2A  
          inet addr:192.168.11.1  Bcast:192.168.11.255  Mask:255.255.255.0
          inet6 addr: fe80::8c82:65ff:fe61:f32a/64 Scope:Link
          inet6 addr: fd33:4884:f48e::1/60 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:7525 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3576 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:620216 (605.6 KiB)  TX bytes:1469123 (1.4 MiB)

docker0   Link encap:Ethernet  HWaddr 02:42:A8:08:8E:24  
          inet addr:172.17.0.1  Bcast:172.17.255.255  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

dummy0    Link encap:Ethernet  HWaddr B2:45:0C:C9:BE:B3  
          BROADCAST NOARP  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

erspan0   Link encap:Ethernet  HWaddr 00:00:00:00:00:00  
          BROADCAST MULTICAST  MTU:1450  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth0      Link encap:Ethernet  HWaddr 8E:82:65:61:F3:29  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:27 

eth1      Link encap:Ethernet  HWaddr 8E:82:65:61:F3:2A  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:7525 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3810 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:620216 (605.6 KiB)  TX bytes:1468807 (1.4 MiB)

gre0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          NOARP  MTU:1476  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

gretap0   Link encap:Ethernet  HWaddr 00:00:00:00:00:00  
          BROADCAST MULTICAST  MTU:1462  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:492 errors:0 dropped:0 overruns:0 frame:0
          TX packets:492 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:37333 (36.4 KiB)  TX bytes:37333 (36.4 KiB)

sit0      Link encap:IPv6-in-IPv4  
          NOARP  MTU:1480  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

wlan0     Link encap:Ethernet  HWaddr 34:20:03:B6:36:3D  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

wlan1     Link encap:Ethernet  HWaddr 36:20:03:B6:36:3D  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)`

**Comment by qinkun1994** [comment]
cat /etc/config/wireless

config wifi-device 'radio0'
        option type 'mac80211'
        option path 'platform/ff5c0000.usb/usb1/1-1/1-1:1.0'
        option channel '36'
        option band '5g'
        option htmode 'NOHT'
        option country 'US'

config wifi-iface 'default_radio0'
        option device 'radio0'
        option network 'lan'
        option mode 'ap'
        option ssid 'OpenWrt'
        option encryption 'none'

**Comment by DHDAXCW** [comment]
修改后建议重启即可

**Comment by qinkun1994** [comment]
> 

然后就起不来了，无线也没有，重新上电，红灯一直闪， lan口连上电脑，绿灯不闪了，DHCP拿不到IP。我必须长按reset恢复才行

**Comment by qinkun1994** [comment]
### 硬件是好的，野火自己的固件可以生成wifi，只是他没有中继转发。如你所说，无线界面直接保存，重启，只能登陆，网页进不了了，wifi也没有生成
![image](https://user-images.githubusercontent.com/33141476/161360172-4efe7a3b-236e-4259-b380-747e8b3822dd.png)

**Comment by qinkun1994** [comment]
ifconfig -a 也不会有响应

**Comment by qinkun1994** [comment]
> 改后建议重启即可

麻烦关注一下，谢谢  ，基本功能 不能使用很捉急 -_-!     命令行敲个wifi指令也会卡死

**Comment by DHDAXCW** [comment]
建议刷最新版本固件，或者电报群私我提供帮助

**Comment by qinkun1994** [comment]
0325日期的固件可以支持，作者后面会修复。    野火官方说硬件无线网卡RTL8723不支持中继转发功能，保持怀疑。
